import { Platform, StatusBar, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  itemDate: {
    fontSize: 12,
    color: '#718096',
  },
  commissionText: {
    fontSize: 12,
    color: '#718096',
    marginLeft: 10,
  },
  itemDetails: {
    flex: 1,
  },
  itemSubtitle: {
    fontSize: 12,
    color: '#718096',
    marginTop: 2,
  },
  itemBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  statusBadge: {
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 8,
  },
  statusCompleted: {
    backgroundColor: '#E6FFFA',
  },
  statusPending: {
    backgroundColor: '#FEFCBF',
  },
  statusText: {
    fontSize: 10,
    fontWeight: '500',
  },
  statusCompletedText: {
    color: '#38A169',
  },
  statusPendingText: {
    color: '#D69E2E',
  },
  amountContainer: {
    alignItems: 'flex-end',
  },
  commissionRate: {
    fontSize: 10,
    color: '#718096',
    marginTop: 4,
  },
  activeFiltersContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#F7FAFC',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#5E72E4',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  filterChipText: {
    color: '#FFF',
    fontSize: 12,
  },
  filterChipClose: {
    marginLeft: 6,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EBF4FF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  activeFilter: {
    backgroundColor: '#5E72E4',
  },
  activeFilterText: {
    color: '#FFF',
  },
  filterButtonText: {
    color: '#5E72E4',
    fontWeight: '500',
    fontSize: 14,
    marginLeft: 8,
  },
  sectionSubText: {
    fontSize: 12,
    color: '#718096',
    marginTop: 2,
  },
  summaryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginBottom: 16,
    gap: 10,
  },
  summaryCard: {
    flex: 1,
    borderRadius: 12,
    padding: 16,
    backgroundColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginTop: 8,
  },
  commissionCard: {
    borderTopWidth: 10,
    borderTopColor: '#4C51BF',
  },
  paymentCard: {
    borderTopWidth: 10,
    borderTopColor: '#38A169',
  },
  pendingCard: {
    borderTopWidth: 10,
    borderTopColor: '#DD6B20', 
  },
  summaryLabel: {
    fontSize: 15, 
    color: '#718096',
    marginBottom: 8,
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2D3748',
  },
  pendingValue: {
    color: '#E53E3E',
  }, 

  dateFilterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EDF2F7',
    padding: 8,
    marginHorizontal: 16,
    borderRadius: 8,
    marginBottom: 12,
  },
  dateFilterText: {
    fontSize: 14,
    color: '#4A5568',
    marginRight: 8,
  },
  monthSectionHeader: {
    backgroundColor: '#EBF4FF',
  },
  container: {
    flex: 1,
    backgroundColor: '#F7FAFC',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F7FAFC',
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 40,
    paddingBottom: 20,
    backgroundColor: "#5E72E4",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFF",
    marginLeft: 15,
  },
  calendarButton: {
    padding: 8,
  },
  summaryLabel1: {
    fontSize: 14,
    color: '#718096',
    marginBottom: 5,
    textAlign: 'center',
  },
  pendingValue1: {
    color: '#E53E3E',
  },
  tabContainer: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginBottom: 10,
    backgroundColor: '#EDF2F7',
    borderRadius: 8,
    padding: 5,
  },
  tabButton: {
    flex: 1,
    padding: 10,
    borderRadius: 6,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: '#5E72E4',
  },
  tabText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#718096',
  },
  activeTabText: {
    color: '#FFF',
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5E72E4',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginHorizontal: 16,
    marginBottom: 8,
  },
  editButtonText: {
    color: '#FFF',
    marginLeft: 8,
    fontWeight: '500',
  },
  selectionModeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#4A5568',
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 8,
  },
  cancelSelectionButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cancelSelectionText: {
    color: '#FFF',
    marginLeft: 8,
  },
  selectedCountText: {
    color: '#FFF',
    fontWeight: '500',
  },
  deleteSelectionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E53E3E',
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  deleteSelectionText: {
    color: '#FFF',
    marginLeft: 8,
  },
  checkboxContainer: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#CBD5E0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxSelected: {
    backgroundColor: '#5E72E4',
    borderColor: '#5E72E4',
  },
  payButton: {
    flexDirection: 'row',
    backgroundColor: '#5E72E4',
    borderRadius: 8,
    padding: 12,
    marginHorizontal: 15,
    marginBottom: 15,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  payButtonText: {
    color: '#FFF',
    fontWeight: '600',
    fontSize: 15,
  },
  listContainer: {
    paddingBottom: 20,
  },
  sectionHeader: {
    backgroundColor: '#F7FAFC',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
  },
  sectionHeaderText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A5568',
  },
  sectionHeaderAmount: {
    fontSize: 20,
    fontWeight: '600',
    color: '#5E72E4',
    paddingRight: 15,
  },
  sectionHeaderAmount1: {
    fontSize: 20,
    fontWeight: '600',
    color: '#38A169',
    paddingRight: 15,
  },
  itemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 15,
    marginHorizontal: 15,
    marginVertical: 5,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  itemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  itemIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EBF4FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  itemTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2D3748',
  },
  itemTime: {
    fontSize: 12,
    color: '#718096',
    marginTop: 4,
  },
  itemAmount: {
    fontSize: 15,
    fontWeight: '700',
  },
  commissionAmount: {
    color: '#5E72E4',
  },
  paymentAmount: {
    color: '#38A169',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyText: {
    textAlign: "center",
    color: "#666",
    marginTop: 16,
    fontSize: 18,
    fontWeight: "500",
  },
  loadingMoreContainer: {
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  loadingMoreText: {
    marginLeft: 10,
    color: '#718096',
  },
  endOfListContainer: {
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  endOfListText: {
    color: '#718096',
    fontSize: 14,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#FFF',
    borderRadius: 15,
    width: '90%',
    maxHeight: '80%',
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D3748',
  },
  modalScrollContainer: {
  flexGrow: 1,
  justifyContent: 'center',
  padding: 20,
},
  modalContent: {
    paddingVertical: 10,
  },
  modalSubtitle: {
    fontSize: 15,
    color: '#4A5568',
    marginBottom: 15,
  },
  paymentSummary: {
    marginVertical: 15,
    backgroundColor: '#F7FAFC',
    borderRadius: 10,
    padding: 15,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  paymentInput: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    padding: 15 ,
    marginBottom: 20,
    fontSize: 15,
    color: '#2D3748',
  },
  submitButton: {
    backgroundColor: '#5E72E4',
    borderRadius: 8,
    padding: 15,
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
  errorText: {
  color: '#E53E3E',
  fontSize: 14,
  marginTop: 1,
  textAlign: 'center',
},
disabledButton: {
  backgroundColor: '#CBD5E0',
},

});